python -W ignore Scripts\County_MedianListingPrice_AllHomes.py
python -W ignore Scripts\County_MedianListingPricePerSqft_AllHomes.py
python -W ignore Scripts\County_MedianValuePerSqft_AllHomes.py
python -W ignore Scripts\County_Zhvi_AllHomes.py
python Scripts\GeoFRED_All_Transactions_House_Price_Index.py
python Scripts\GeoFRED_Homeownership_Rate_by_County.py
python Scripts\GeoFRED_New_Private_Housing_Structures.py
python Scripts\Land_Measures.py

pause